[pytest]
testpaths = tests
pythonpath = .
addopts = -ra --strict-markers --basetemp=.pytest_tmp
filterwarnings =
    ignore::DeprecationWarning
tmp_path_retention_count = 3
tmp_path_retention_policy = failed
